#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb  5 17:00:51 2019

@author: bradly
"""

import pandas as pd
import datashader as ds
import datashader.transfer_functions as tf
#new_array = np.array((np.array(held_FRs_cond2_2)-np.array(held_FRs_cond1_2))/np.array(held_FRs_cond1_2)).T
hFR1 = np.array(held_FRs_cond1_2); hFR2 = np.array(held_FRs_cond2_2)

hFR1[hFR1==0]=0.0001;hFR2[hFR2==0]=0.0001;

new_array = (hFR2-hFR1)/hFR1
#df = pd.DataFrame(new_array)

x= np.double(np.arange(new_array.shape[0]))
x[-1] = np.nan; 

df2 = pd.DataFrame({'x': np.tile(x,new_array.shape[1]), 'y': new_array.flatten(order='F')})	
canvas = ds.Canvas(x_range = (df2['x'].min() - 10, df2['x'].max() + 10), 
			   y_range = (df2['y'].min() - 10, df2['y'].max() + 10),
			   plot_height=1200, plot_width=1600)
agg = canvas.line(df2, x='x', y='y', agg= ds.count())
img = tf.shade(agg, how='eq_hist',cmap=['lightblue','darkblue'])
img


fig,ax = plt.subplots(1, 1, figsize = (8,6), dpi = 200)
#ax.title('Held Unit Firing Rate Histogram' +'\n' + 'Animals: %i, Window: %i ms, Step: %i ms' % (np.size(dirs_animals_1[0]),params[1], params[2]) + '\n' + 'Units: %i, Smoothing Spline: %ith order' % (np.size(held_FRs_cond1_2,axis=0), params[3]))
#ax.xlabel('Time from injection (ms)')
#ax.ylabel(r'$\Delta$'+ ' Firing rate (Hz)')

#ax.set_xticks(np.linspace(0, 1600, 10))
#ax.set_xticklabels(np.floor(np.linspace(np.min(x[:-1]), np.max(x[:-1]), 10)))
#ax.set_yticks(np.linspace(-1.5, 1.5, 10))
#ax.set_yticklabels(np.floor(-1.5, 1.5), 10)
ax.imshow(img)


fig,ax = plt.subplots(1, 1, figsize = (8,6), dpi = 200)
# Start plotting
ax.imshow(img,origin='lower')
fig.savefig(save_name+'abuzar.png')