conda install -c conda-forge mamba -y
mamba install -c conda-forge bokeh=1.4.0 -y
mamba install -c conda-forge datashader=0.13.0 -y
mamba install -c conda-forge imageio=2.6.1 -y
mamba install -c conda-forge matplotlib=3.3.4 -y
mamba install -c conda-forge numba=0.53.1 -y
mamba install -c conda-forge numpy=1.19.5 -y
mamba install -c conda-forge pandas=1.1.5 -y
mamba install -c conda-forge psutil=5.8.0 -y
mamba install -c conda-forge pytables=3.6.1 -y
mamba install -c conda-forge scikit-learn=0.22.1 -y
